fits:
  flip_for_ds9: false
hpc:
  hpc_mode: false
  iterations_per_update: 5000
model:
  ignore_prior_limits: false
output:
  force_pickle_overwrite: false
  info_whitespace_length: 80
  log_file: output.log
  log_level: INFO
  log_to_file: false
  model_results_decimal_places: 3
  remove_files: false
  samples_to_csv: true
test:
  check_likelihood_function: false  # if True, when a search is resumed the likelihood of a previous sample is recalculated to ensure it is consistent with the previous run.