interpolate:
  func:
    MockInterpolateClass: true
  func_off:
    MockInterpolateClass: false
  ndarray_1d_from_grid:
    MockGridLikeIteratorObj: true
    MockInterpolateObj: true
  ndarray_2d_from_grid:
    MockGridLikeIteratorObj: true
    MockInterpolateObj: true
# Certain light and mass profile calculations become ill defined at (0.0, 0.0) or close to this value. This can lead
# to numerical issues in the calculation of the profile, for example a np.nan may arise, crashing the code. 
  
# To avoid this, we set a minimum value for the radial coordinate of the profile. If the radial coordinate is below 
# this value, it is rounded up to this value. This ensures that the profile cannot receive a radial coordinate of 0.0.

# For example, if an input grid coordinate has a radial coordinate of 1e-12, for most profiles this will be rounded up
# to radial_minimum=1e-08. This is a small enough value that it should not impact the results of the profile calculation.

radial_minimum:
  radial_minimum:
    EllipticalBrokenPowerLaw: 1.0e-08
    EllipticalCoreSersic: 1.0e-08
    EllipticalCoredIsothermal: 1.0e-08
    EllipticalCoredPowerLaw: 1.0e-08
    EllipticalDevVaucouleurs: 1.0e-08
    EllipticalExponential: 1.0e-08
    EllipticalGaussian: 1.0e-08
    EllipticalGeneralizedNFW: 1.0e-08
    EllipticalIsothermal: 1.0e-08
    EllipticalMassProfile: 1.0e-08
    EllipticalNFW: 1.0e-08
    EllipticalProfile: 1.0e-08
    EllipticalSersic: 1.0e-08
    EllipticalSersicGradient: 1.0e-08
    ExternalShear: 1.0e-08
    MassSheet: 1.0e-08
    MockGridRadialMinimum: 2.5
    PointMass: 0.0
    PowerLaw: 1.0e-08
    SphericalBrokenPowerLaw: 1.0e-08
    SphericalCoreSersic: 1.0e-08
    SphericalCoredIsothermal: 1.0e-08
    SphericalCoredPowerLaw: 1.0e-08
    SphericalDevVaucouleurs: 1.0e-08
    SphericalExponential: 1.0e-08
    SphericalGaussian: 1.0e-08
    SphericalGeneralizedNFW: 1.0e-08
    SphericalIsothermal: 1.0e-08
    SphericalNFW: 1.0e-08
    SphericalPowerLaw: 1.0e-08
    SphericalSersic: 1.0e-08
    SphericalSersicGradient: 1.0e-08
    SphericalTruncatedNFW: 1.0e-08
    SphericalTruncatedNFWChallenge: 1.0e-08
    SphericalTruncatedNFWMCR: 1.0e-08
