GridSearch:
  general:
    number_of_cores: 2
    step_size: 0.1
mcmc:
  Emcee:
    auto_correlations:
      change_threshold: 0.01
      check_for_convergence: true
      check_size: 100
      required_length: 50
    initialize:
      ball_lower_limit: 0.49
      ball_upper_limit: 0.51
      method: ball
    parallel:
      number_of_cores: 1
    printing:
      silence: false
    prior_passer:
      sigma: 3.0
      use_errors: true
      use_widths: true
    run:
      nsteps: 2000
    search:
      nwalkers: 50
    updates:
      iterations_per_update: 2500
      log_every_update: 1
      model_results_every_update: 1
      remove_state_files_at_end: true
      visualize_every_update: 1
mock:
  MockOptimizer:
    initialize:
      method: prior
    printing:
      silence: false
    prior_passer:
      sigma: 3.0
      use_errors: true
      use_widths: true
    updates:
      iterations_per_update: 2500
      log_every_update: 1
      model_results_every_update: 1
      remove_state_files_at_end: true
      visualize_every_update: 1
  MockSearch:
    initialize:
      method: prior
    printing:
      silence: false
    prior_passer:
      sigma: 3.0
      use_errors: true
      use_widths: true
    search: {}
    updates:
      iterations_per_update: 2500
      log_every_update: 1
      model_results_every_update: 1
      remove_state_files_at_end: true
      visualize_every_update: 1
nest:
  DynestyDynamic:
    initialize:
      method: prior
    parallel:
      force_x1_cpu: false
      number_of_cores: 1
    printing:
      silence: false
    prior_passer:
      sigma: 3.0
      use_errors: true
      use_widths: true
    search:
      bootstrap: 0
      bound: multi
      enlarge: -1.0
      evidence_tolerance: 0.01
      fmove: 0.9
      logl_max: .inf
      max_move: 100
      maxcall: null
      maxcall_init: null
      maxiter: null
      maxiter_init: null
      n_effective_init: 0
      sample: auto
      sampling_efficiency: 0.5
      slices: 5
      update_interval: -1.0
      walks: 25
    updates:
      iterations_per_update: 2500
      log_every_update: 1
      model_results_every_update: 1
      remove_state_files_at_end: true
      visualize_every_update: 1
  DynestyStatic:
    initialize:
      method: prior
    parallel:
      number_of_cores: 1
    printing:
      silence: false
    prior_passer:
      sigma: 3.0
      use_errors: true
      use_widths: true
    search:
      bootstrap: 0
      bound: multi
      enlarge: -1.0
      fmove: 0.9
      logl_max: .inf
      max_move: 100
      maxcall: null
      maxiter: null
      n_effective: 0
      nlive: 150
      sample: auto
      sampling_efficiency: 0.5
      slices: 5
      update_interval: -1.0
      walks: 25
    updates:
      iterations_per_update: 2500
      log_every_update: 1
      model_results_every_update: 1
      remove_state_files_at_end: true
      visualize_every_update: 1
optimize:
  DownhillSimplex:
    search:
      disp: 1
      ftol: 0.0001
      full_output: 0
      maxfun: null
      maxiter: null
      retall: 0
      xtol: 0.0001
    updates:
      iterations_per_update: 2500
      log_every_update: 1
      model_results_every_update: 1
      remove_state_files_at_end: true
      visualize_every_update: 1
