plots:
  dataset:
    data: true
    data_logy: false
    absolute_signal_to_noise_map: false
    cosmic_ray_map: true
    data: true
    inverse_noise_map: false
    noise_map: false
    noise_scaling_map_dict: false
    potential_chi_squared_map: Fals
    pre_cti_data: true
    signal_to_noise_map: false
    subplot_dataset: true
  fit:
    all_at_end_fits: false
    all_at_end_png: true
    chi_squared_map: false
    data: true
    data_logy: false
    data: true
    noise_map: false
    noise_scaling_map_dict: false
    normalized_residual_map: true
    post_cti_data: true
    pre_cti_data: true
    residual_map: true
    signal_to_noise_map: false
    subplot_fit: true
  other:
    stochastic_histogram: false
  positions:
    image_with_positions: true
