general:
  general:
    backend: default                  # The matploblib backend used for visualization. `default` uses the system default, can specifiy specific backend (e.g. TKAgg, Qt5Agg, WXAgg).
    imshow_origin: upper              # The `origin` input of `imshow`, determining if pixel values are ascending or descending on the y-axis.
    zoom_around_mask: true            # If True, plots of data structures with a mask automatically zoom in the masked region.
    symmetric_cmap_value: 100.0       # The vmin and vmax of all pre-cti data residual-maps.
    subplot_ascending_fpr: true       # If True, subplots showing FPR / EPER trails of many datasets are in ascending order of FPR value.
plots:
  dataset:
    data: true
    data_logy: false
    cosmic_ray_map: true
    noise_map: false
    noise_scaling_map_dict: false
    pre_cti_data: true
    signal_to_noise_map: false
    subplot_dataset: true
  fit:
    all_at_end_fits: false
    all_at_end_png: true
    chi_squared_map: false
    data: true
    data_logy: false
    noise_map: false
    noise_scaling_map_dict: false
    normalized_residual_map: true
    post_cti_data: true
    pre_cti_data: true
    residual_map: true
    signal_to_noise_map: false
    subplot_fit: true
  other:
    stochastic_histogram: false
  positions:
    image_with_positions: true
