TrapInstantCapture:
  density:
    gaussian_limits:
      lower: 0.0
      upper: inf
    lower_limit: 0.0
    type: Uniform
    upper_limit: 30.0
    width_modifier:
      type: Relative
      value: 0.5
  release_timescale:
    gaussian_limits:
      lower: 0.0
      upper: inf
    lower_limit: 0.0
    type: Uniform
    upper_limit: 30.0
    width_modifier:
      type: Relative
      value: 0.5
