#!/bin/bash -l

#SBATCH -J serial_runner_high_res_cosma
#SBATCH -n 8
#SBATCH -o ../output/serial_runner_high_res_cosma_output.%A.%a.out
#SBATCH -e ../output/serial_runner_high_res_cosma_error.%A.%a.err
#SBATCH -p cosma # also cordelia
#SBATCH -A durham
#SBATCH -t 24:00:00   # longest job
#SBATCH --mail-type=END                          # notifications for job done & fail
#SBATCH --mail-user=email@durham.ac.uk

module purge
module load python/3.6.5
source /cosma/home/durham/pdtw24/PyAutoCTI_jam/bin/activate

# Run the program, note $SLURM_ARRAY_TASK_ID is set to the array number.

python3 $WORKSPACE/runners/serial_runner_high_res_cosma.py 1