CCDPhase:
  full_well_depth:
    type: Uniform
    lower_limit: 0.0
    upper_limit: 200000.0
    width_modifier:
      type: Absolute
      value: 0.2
    gaussian_limits:
      lower: 0.0
      upper: 1.0
  well_fill_power:
    type: Uniform
    lower_limit: 0.0
    upper_limit: 1.0
    width_modifier:
      type: Absolute
      value: 0.2
    gaussian_limits:
      lower: 0.0
      upper: 1.0
  well_notch_depth:
    type: Uniform
    lower_limit: 0.0
    upper_limit: 1.0
    width_modifier:
      type: Absolute
      value: 0.2
    gaussian_limits:
      lower: 0.0
      upper: 1.0
  first_electron_fill:
    type: Constant
    value: 0.0