HyperCINoiseScalar:
  scale_factor:
    type: Uniform
    lower_limit: 0.0
    upper_limit: 10.0
    width_modifier:
      type: Relative
      value: 0.5
    gaussian_limits:
      lower: 0.0
      upper: inf
