TrapInstantCapture:
  density:
    type: Uniform
    lower_limit: 0.0
    upper_limit: 10.0
    width_modifier:
      type: Relative
      value: 0.5
    gaussian_limits:
      lower: 0.0
      upper: inf
  release_timescale:
    type: Uniform
    lower_limit: 0.0
    upper_limit: 50.0
    width_modifier:
      type: Relative
      value: 0.5
    gaussian_limits:
      lower: 0.0
      upper: inf
  fractional_volume_full_exposed:
    type: Constant
    value: 0.0
  fractional_volume_none_exposed:
    type: Constant
    value: 0.0
TrapInstantCaptureContinuum:
  density:
    type: Uniform
    lower_limit: 0.0
    upper_limit: 10.0
    width_modifier:
      type: Relative
      value: 0.5
    gaussian_limits:
      lower: 0.0
      upper: inf
  release_timescale:
    type: Uniform
    lower_limit: 0.0
    upper_limit: 50.0
    width_modifier:
      type: Relative
      value: 0.5
    gaussian_limits:
      lower: 0.0
      upper: inf
  release_timescale_sigma:
    type: Uniform
    lower_limit: 0.0
    upper_limit: 1.0
    width_modifier:
      type: Relative
      value: 0.5
    gaussian_limits:
      lower: 0.0
      upper: inf
