name: Tests

on: [push, pull_request]

jobs:
  unittest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, "3.10"]
    steps:
    - name: Checkout PyAutoConf
      uses: actions/checkout@v2
      with:
        repository: rhayes777/PyAutoConf
        path: PyAutoConf
    - name: Checkout PyAutoFit
      uses: actions/checkout@v2
      with:
        repository: rhayes777/PyAutoFit
        path: PyAutoFit
    - name: Checkout PyAutoArray
      uses: actions/checkout@v2
      with:
        repository: Jammy2211/PyAutoArray
        path: PyAutoArray
    - name: Checkout PyAutoCTI
      uses: actions/checkout@v2
      with:
        repository: Jammy2211/PyAutoCTI
        path: PyAutoCTI
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Extract branch name
      shell: bash
      run: |
        cd PyAutoCTI
        echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - name: Change to same branch if exists in deps
      shell: bash
      run: |
        export PACKAGES=("PyAutoConf" "PyAutoArray" "PyAutoFit")
        export BRANCH="${{ steps.extract_branch.outputs.branch }}"
        for PACKAGE in ${PACKAGES[@]}; do
          pushd $PACKAGE
          export existed_in_remote=$(git ls-remote --heads origin ${BRANCH})

          if [[ -z ${existed_in_remote} ]]; then
            echo "Branch $BRANCH did not exist in $PACKAGE"
          else
            echo "Branch $BRANCH did exist in $PACKAGE"
            git fetch
            git checkout $BRANCH
          fi
          popd
        done
    - name: Install dependencies
      run: |
        pip3 install --upgrade pip
        pip3 install setuptools
        pip3 install wheel
        pip3 install pytest coverage pytest-cov
        pip3 install -r PyAutoConf/requirements.txt
        pip3 install -r PyAutoFit/requirements.txt
        pip3 install -r PyAutoArray/requirements.txt
        pip3 install -r PyAutoArray/optional_requirements.txt
        pip3 install -r PyAutoCTI/requirements.txt
        pip3 install -r PyAutoCTI/optional_requirements.txt
    - name: Run tests
      run: |
        export ROOT_DIR=`pwd`
        export PYTHONPATH=$PYTHONPATH:$ROOT_DIR/PyAutoConf
        export PYTHONPATH=$PYTHONPATH:$ROOT_DIR/PyAutoFit
        export PYTHONPATH=$PYTHONPATH:$ROOT_DIR/PyAutoArray
        export PYTHONPATH=$PYTHONPATH:$ROOT_DIR/PyAutoCTI
        pushd PyAutoCTI
        pytest --cov autocti --cov-report xml:coverage.xml
